### ISSUE TITLE
About adding documents to shadowsocks-libev

### ISSUE THREAD

**Issue by madeye** [vimagick/dockerfiles#11]
Hi Vimagick,

First of all, awesome project!

Could you contribute your docker files and documents of shadowsocks-libev to the upstream? We'd like to update them here: https://github.com/shadowsocks/shadowsocks-libev/tree/master/docker.

Thanks,
Max

**Comment by vimagick** [comment]
@madeye With pleasure. I'll do it as soon as possible.

**Comment by L-Jovi** [comment]
truest project with good contributor : )

**Comment by vimagick** [comment]
:sob: I have difficulty to write a long english documentation.

**Comment by madeye** [comment]
I think you can open a pull request for docker files first, then we would help to refine the documents.

**Comment by vimagick** [comment]
Good idea. I'll try my best.

**Comment by vimagick** [comment]
Merged: https://github.com/shadowsocks/shadowsocks-libev/tree/master/docker/alpine
