### ISSUE TITLE
urlwatch - strip not working/missing

### ISSUE THREAD

**Issue by olosz** [vimagick/dockerfiles#117]
Hi,
I'm a noob but my impression is that strip is not working (nor is available) in vimagick/urlwatch container.
Please can you include this, as this is a-must-have feature for parsing (html2text,strip) and comparing text?

If you think this makes no sense, I'll do my best to provide further explaination by examples.

Thanks and best regards,
olo

**Comment by vimagick** [comment]
Please try the latest image. Thanks
