### ISSUE TITLE
i can't connect, use shadowsocks client for osx

### ISSUE THREAD

**Issue by Chihpin** [vimagick/dockerfiles#13]
core@coreos ~ $ docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                              NAMES
2c4d89ac118a        vimagick/shadowsocks-libev   "/bin/sh -c 'ss-serve"   4 hours ago         Up 4 hours          8388/udp, 0.0.0.0:8388->8388/tcp   shadowsocks_shadowsocks_1

core@coreos ~ $ docker attach
docker: "attach" requires 1 argument.
See 'docker attach --help'.

Usage:	docker attach [OPTIONS] CONTAINER

Attach to a running container
core@coreos ~ $ docker attach 2c
 2016-03-26 14:02:17 ERROR: authentication error from 1**.1**.2**.223
 2016-03-26 14:02:47 ERROR: invalid header with addr type 68
 2016-03-26 14:02:47 ERROR: failed to handshake with 1**.1**.2**.223
 2016-03-26 14:02:54 ERROR: invalid header with addr type -126
 2016-03-26 14:02:54 ERROR: failed to handshake with 1**.1**.2**.223

**Comment by vimagick** [comment]
Did you try it on linux?

**Comment by vimagick** [comment]
I'm running ss-client on my MacOSX with this supervisor config:

```
[program:shadowsocks]
command = ss-local -s 1.2.3.4
                   -p 8388
                   -b 127.0.0.1
                   -l 1080
                   -k XXXXXXXXX
                   -m chacha20
redirect_stderr = true
```
It works fine.

**Comment by Chihpin** [comment]
Thanks!    
I connetct ss server with  the client app. Now,  i will install ss-local and try again.

**Comment by Chihpin** [comment]
## this is my docker-compose.yml

shadowsocks:
  image: vimagick/shadowsocks-libev
  ports:
    - "8388:8388"
  environment:
    - PASSWORD = Mh8qiJ39S
  restart: always

## but inspect container,  'password' is null:

"Config": {
        "Hostname": "2c4d89ac118a",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "8388/tcp": {},
            "8388/udp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "PASSWORD = Mh8qiJ39S",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "SS_VER=2.4.5",
            "SS_URL=https://github.com/shadowsocks/shadowsocks-libev/archive/v2.4.5.tar.gz",
            "SS_DIR=shadowsocks-libev-2.4.5",
            "SS_DEP=autoconf build-base curl libtool linux-headers openssl-dev",
            "SERVER_ADDR=0.0.0.0",
            "SERVER_PORT=8388",
            "PASSWORD=",
            "METHOD=aes-256-cfb",
            "TIMEOUT=300",
            "DNS_ADDR=8.8.8.8"
        ],
        "Cmd": [
            "/bin/sh",
            "-c",
            "ss-server -s $SERVER_ADDR               -p $SERVER_PORT               -k ${PASSWORD:-$(hostname)}               -m $METHOD               -t $TIMEOUT               --fast-open               -d $DNS_ADDR               -u"
        ],

**Comment by vimagick** [comment]
Please make some change to `docker-compose.yml`

From:

```
  - PASSWORD = Mh8qiJ39S
```
To:

```
  - PASSWORD=Mh8qiJ39S
```

**Comment by Chihpin** [comment]
Thanks !  It works! 😀

**Comment by vimagick** [comment]
Good
