### ISSUE TITLE
Update Murmur to 1.3.0

### ISSUE THREAD

**Issue by davidpp** [vimagick/dockerfiles#133]
Thought the image was up to date, but realized it's still version 1.2

Mumble/Murmur is now at 1.3:
Ref:  https://github.com/mumble-voip/mumble/releases

**Comment by bxkx** [comment]
Is this ever going to be updated?

**Comment by vimagick** [comment]
Upgraded to 1.3.4: https://hub.docker.com/r/vimagick/murmur/dockerfile
