### ISSUE TITLE
Update urlwatch to 2.18

### ISSUE THREAD

**Issue by markisoke** [vimagick/dockerfiles#134]
urlwatch 2.18 contains a new key feauture called re.sub and it would be really helpfull for my use case.

**Comment by dhlavaty** [comment]
There is urlwatch 2.21 now, with great `--test-reporter` feature. Pls update this on docker hub

**Comment by robgmills** [comment]
Looks like there was recent build of the container image pushed to docker hub on 11 January 2021:

<img width="277" alt="Screen Shot 2021-01-21 at 8 12 57 PM" src="https://user-images.githubusercontent.com/1627601/105432176-bc203880-5c1c-11eb-954e-78b66216b14f.png">

This image seems to be running version `2.22` of urlwatch:

```sh
$ docker-compose up -d
$ docker-compose exec urlwatch sh
~/.urlwatch # pip3 show urlwatch
Name: urlwatch
Version: 2.22
Summary: urlwatch monitors webpages for you
Home-page: https://thp.io/2008/urlwatch/
Author: Thomas Perl
Author-email: m@thp.io
License: BSD
Location: /usr/lib/python3.8/site-packages
Requires: minidb, PyYAML, requests, keyring, appdirs, lxml, cssselect
Required-by:
```

And I was able to successfully use the `--test-reporter` option to test integration with my Slack workspace.

**Comment by vimagick** [comment]
It's running urlwatch 2.22 now. 🎉
