### ISSUE TITLE
Cannot build urlwatch docker image - python/pip problem

### ISSUE THREAD

**Issue by dhlavaty** [vimagick/dockerfiles#154]
I wanted to build `urlwatch` docker image by myself (as it is quite outdated now), but `docker build` ends up with Python problem:

```sh
# docker build -t myurlwatch https://raw.githubusercontent.com/vimagick/dockerfiles/master/urlwatch/Dockerfile

+ python3 -m pip install appdirs cssselect keyring lxml minidb pyyaml requests chump urlwatch
/usr/bin/python3: No module named pip
```

**Comment by vimagick** [comment]
I've updated the Dockerfile: https://github.com/vimagick/dockerfiles/blob/master/urlwatch/Dockerfile
Please try again.
