### ISSUE TITLE
OpenCart mysql image not found

### ISSUE THREAD

**Issue by albertvp** [vimagick/dockerfiles#16]
Hi there, great to find your docker images! :+1: 

I'm trying to use it for [OpenCart](https://github.com/vimagick/dockerfiles/blob/master/opencart/docker-compose.yml) but I have this [error](https://forum.opencart.com/viewtopic.php?f=181&t=143341
).

I'm running docker on a OS X with [dinghy](https://github.com/codekitchen/dinghy), without proxy seems to work pretty well.
I tried to put different Hostnames including the docker-machine ip but had no luck.

Do you think might be a different ip for the hostname or should I try with ubuntu?

Moreover, how can I initialize the db with a sql dump file?
Thanks

**Comment by vimagick** [comment]
If you run mysql on another server (IP: `w.x.y.z`).
In the installation page, you need to point the database host to `w.x.y.z`.

**Comment by vimagick** [comment]
Take a look at [this](https://hub.docker.com/_/mysql/) page. In the middle, there is a `Initializing a fresh instance` section.

**Comment by albertvp** [comment]
> If you run mysql on another server (IP: w.x.y.z).

I'm running the original mysql docker volume you have specified in the `docker-compose.yml` and I'm asking for that IP, where can I find it? Is not the same of the `docker-machine ip`?

**Comment by vimagick** [comment]
I use `--link mysql` option, so you can access it via hostname `mysql`.

**Comment by albertvp** [comment]
```
$> docker exec -it mysql_1 bash
root@#> ip addr show eth0
```
