### ISSUE TITLE
urlwatch: Allow configuration of crontab entry

### ISSUE THREAD

**Issue by schildbach** [vimagick/dockerfiles#160]
Currently it appears to be hardcoded to every half hour. I would like to use an argument or environment variable to change that (without rebuilding the docker image from the dockerfile).

**Comment by vimagick** [comment]
If you want to change the interval, you can mount a crontab config file.

`-v /path/to/your/file:/etc/crontabs/root`

**Comment by vimagick** [comment]
@robgmills Thanks
