### ISSUE TITLE
MPD: [Synology Docker] Cannot start

### ISSUE THREAD

**Issue by vkostas** [vimagick/dockerfiles#171]
Tried several times to run vimacgick-MPD docker in Synology DS415+ without success.
No matter what I tried, I get always **standard_init_linux.go:222: exec user process caused "operation not permitted"**.
I can successfully run MPD from IPKG/OPKG bootstrap but their version is kind of old (0.20/0.21.25), and OPKG cannot compile further releases due to C++ version limitation. 
FYI, I specify my own mpd.conf file and everything runs smoothly with IPKG/OPKG.
The last resort was to run docker container with default settings, except mapping local Port = 6600 to Container Port 6600. 
Any hint what might be wrong? Can I somehow see detailed error maybe I understand what's going on?
Thank you!

**Comment by vimagick** [comment]
Try to add `--privileged` to docker command to run

**Comment by vkostas** [comment]
Indeed, there is an option "run container with high privilege". Thanks.
I am getting closer but still not yet there.
I get two errors now:
```
exception: Failed to open '/var/lib/mpd/database': No such file or directory
avahi: Failed to create client: Daemon not running
exception: Failed to open '/var/lib/mpd/state': No such file or directory
```
 I wanted to use my mpd.conf file, to enable bitperfect, and keep mpd config files to dedicated folder outside container.
```
music_directory	    "/volume1/music"
playlist_directory  "/volume1/mpd/vimagick-docker/playlists"
db_file	            "/volume1/mpd/vimagick-docker/mpd.db"
log_file	    "/volume1/mpd/vimagick-docker/mpd.log"
pid_file	    "/volume1/mpd/vimagick-docker/mpd.pid"
state_file	    "/volume1/mpd/vimagick-docker/mpd.state"
sticker_file        "/volume1/mpd/vimagick-docker/mpd.sticker.sql"
```
Should I map 
"/var/lib/mpd/" to my "/volume1/mpd/vimagick-docker/" folder, 
"/var/lib/mpd/music" to my "/volume1/music",
"/etc/mpd.conf" to my "/volume1/mpd/vimagick-docker/mpd.conf"
 and then adapt mpd.conf so it refers to container-like paths?
```
music_directory	    "/var/lib/mpd/music"
playlist_directory  "/var/lib/mpd/playlists"
db_file	            "/var/lib/mpd/mpd.db"
log_file	    "/var/lib/mpd/mpd.log"
pid_file	    "/var/lib/mpd/mpd.pid"
state_file	    "/var/lib/mpd/mpd.state"
sticker_file        "/var/lib/mpd/mpd.sticker.sql"
```

**Comment by vimagick** [comment]
I'm using docker-compose. It works on raspberry pi (4B).
I've tested any other devices yet.

- https://github.com/vimagick/dockerfiles/tree/master/mpd
- https://hub.docker.com/r/easypi/mpd-arm

**Comment by vkostas** [comment]
Thanks @vimagick.

**Comment by vkostas** [comment]
I managed finally to make it work. Thanks. Privilege option helped as well.
Is it true MPD version of this image is 0.21? That's kind of old. 
When do you plan to update to more recent version?
Thanks again. Nice work.
