### ISSUE TITLE
piknik is outdated.

### ISSUE THREAD

**Issue by laishulu** [vimagick/dockerfiles#172]
The latest version of piknik is v0.10,
but the docker is still in v0.9, which not compatible to v0.10 client.

**Comment by vimagick** [comment]
I've updated the Dockerfile with some config path changes.

**Comment by vimagick** [comment]
This is not the latest image

**Comment by laishulu** [comment]
Still not updated yet.
Do you need to push to docker.com manually?

**Comment by laishulu** [comment]
Still the same.

You must have forgotten to push the latest version.

**Comment by laishulu** [comment]
789855

**Comment by vimagick** [comment]
![image](https://user-images.githubusercontent.com/6779585/113672774-bc43b680-96ea-11eb-9740-c434d8d8e6f4.png)
