### ISSUE TITLE
Issue #172 is closed but not resolved.

### ISSUE THREAD

**Issue by laishulu** [vimagick/dockerfiles#173]
https://github.com/vimagick/dockerfiles/issues/172

Please check.

**Comment by vpicone** [comment]
I'm experiencing the same thing, still using old version of piknik

**Comment by vpicone** [comment]
The piknik download URL generated with the latest version number is invalid (not found): https://github.com/jedisct1/piknik/releases/download/0.10.1/piknik-linux_x86_64-0.10.1.tar.gz

Compared to 0.9.1 (downloads properly):
https://github.com/jedisct1/piknik/releases/download/0.9.1/piknik-linux_x86_64-0.9.1.tar.gz 

I opened an issue (https://github.com/jedisct1/piknik/issues/35)

**Comment by vpicone** [comment]
The piknik download URL generated with the latest version number is invalid (not found): https://github.com/jedisct1/piknik/releases/download/0.10.1/piknik-linux_x86_64-0.10.1.tar.gz

Compared to 0.9.1 (downloads properly):
https://github.com/jedisct1/piknik/releases/download/0.9.1/piknik-linux_x86_64-0.9.1.tar.gz 

I opened an issue (https://github.com/jedisct1/piknik/issues/35)

**Comment by laishulu** [comment]
fixed, thanks!
