### ISSUE TITLE
can't connect to Dante outside localhost

### ISSUE THREAD

**Issue by pyed** [vimagick/dockerfiles#18]
I followed the instructions [here](https://github.com/vimagick/dockerfiles/tree/master/dante) now I can do the following on my server:
`curl -x socks5h://username:password@127.0.0.1:1080 https://www.youtube.com`

but I can't do it from my computer:
`curl -x socks5h://username:password@SERVERIP:1080 https://www.youtube.com`

what am I missing ?

**Comment by vimagick** [comment]
I've tested the latest image without problem.
Make sure port 1080/tcp is allowed in firewall.

**Comment by pyed** [comment]
strange, I have no firewall on my server nor my laptop, but changing the port to `3256` solved it.

the curl error was a timeout error.

Thank you.
