### ISSUE TITLE
Publish/Document/etc Scrapyd ARM 

### ISSUE THREAD

**Issue by primeapple** [vimagick/dockerfiles#189]
Hey @vimagick ,
you are doing an awesome job with this repo and I'm very thankful!

I'm primarly interested in Scrapyd. In the folder, you have a Dockerfile for the ARM platform. I have several issues with this:

1. Please add instructions how to use the arm and the amd64 version in the same docker-compose file.
2. Please republish the arm version (I think it resides at https://hub.docker.com/r/easypi/scrapyd-arm ). It changed since last publish.
3. Is there an option to make the dockerfile itself more platform independant? So that we could just use `vimagick/scrapyd` as a base file and it will automatically figure out which platform we're on? (At least for amd64 and arm).

**Comment by vimagick** [comment]
Thank you for your advice. I'll build a multi-arch image.

**Comment by primeapple** [comment]
Awesome. I played a littlebit around with the arm image and noticed, that you need to have `cargo` installed via `apt-get` for compiling of python `cryptography`. So you should add this. I think it can be purged after compilation.

Also you should edit the `docker-compose.yml` files in the `scrapyd/py3` and `scrapyd/arm` folders to use the volume `    - /usr/local/lib/python3.9/dist-packages` instead of `    - /usr/local/lib/python3.7/dist-packages`.

**Comment by vimagick** [comment]
These two images for arm/arm64 were built minutes ago:

- https://hub.docker.com/r/easypi/scrapyd-arm (+cargo)
- https://hub.docker.com/r/easypi/scrapyd-arm64

**Comment by vimagick** [comment]
I hope it works: https://hub.docker.com/r/easypi/scrapyd (pushed manually)
Automated build is not ready now.

**Comment by vimagick** [comment]
I have created a github workflow to build: https://github.com/EasyPi/docker-scrapyd/blob/master/.github/workflows/build.yaml ✅

**Comment by primeapple** [comment]
Awesome, thank you a lot. :)
Works well!
