### ISSUE TITLE
Container Restarts Repeatedly 

### ISSUE THREAD

**Issue by anpjohn** [vimagick/dockerfiles#197]
Continually restarts with this error:

6/Jan/2022 20:09:50 [main.cpp:245] ERROR: An exception occurred during eno3 interface creation[95]: Operation not supported
06/Jan/2022 20:09:50 [main.cpp:303] ERROR: Startup error: missing super-user privileges ?

**Comment by anpjohn** [comment]
Docker compose file contents: 

version: '3'
services:
  ntopng:
    image: vimagick/ntopng
    command: -d /var/lib/ntopng -i eno3 -r 127.0.0.1:6379@0 -w 0.0.0.0:3000
    volumes:
      - ./data/ntopng:/var/lib/ntopng
      - /var/lib/ntopng/ntopng.license:/etc/ntopng.license
    network_mode: host
    restart: unless-stopped
  redis:
    image: redis:alpine
    command: --save 900 1
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    restart: unless-stopped

**Comment by vimagick** [comment]
try `privileged: true`

**Comment by anpjohn** [comment]
that fixed it! thank you.
