### ISSUE TITLE
openconnect: use official package from Alpine

### ISSUE THREAD

**Issue by bjmi** [vimagick/dockerfiles#201]
Since Alpine 3.13 [openconnect package](https://pkgs.alpinelinux.org/packages?name=openconnect&branch=v3.13&repo=&arch=&maintainer=) is immediate avaiable via `apk`.

Please release a new openconnect image by switching to more up to date alpine base image and add package immediately.

Thanks in advance!

**Comment by vimagick** [comment]
updated ✅
