### ISSUE TITLE
tinc-arm missing from Docker Hub

### ISSUE THREAD

**Issue by jordancrawfordnz** [vimagick/dockerfiles#22]
I've been using ``tinc-arm`` and it works great. I tried a re-install today and noticed it seems to be gone from Docker Hub.

Is this intentional? If not, any chance it could be re-uploaded?

**Comment by vimagick** [comment]
It has been moved to [easypi/tinc-arm](https://hub.docker.com/r/easypi/tinc-arm/). I've rewritten the [Dockerfile](https://github.com/vimagick/dockerfiles/tree/master/tinc).
It's not backward compatible. I'm sorry for that.

**Comment by jordancrawfordnz** [comment]
No worries. I'll probably setup a tinc image for the Pi of my own as I run mine as a client.

**Comment by vimagick** [comment]
This is the original [Dockerfile][1] for tinc.

[1]: https://github.com/vimagick/dockerfiles/blob/4953ba1837b55c7e173e1c95100eff6250b7d1b1/tinc/Dockerfile
