### ISSUE TITLE
pptpd error

### ISSUE THREAD

**Issue by newrey** [vimagick/dockerfiles#24]
~/pptpd# docker-compose up
Creating pptpd_pptpd_1
Attaching to pptpd_pptpd_1
pptpd_1  | + iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
pptpd_1  | + pptpd
pptpd_pptpd_1 exited with code 1

**Comment by vimagick** [comment]
Please post your `docker-compose.yml`.
Make sure all config files are available.

**Comment by newrey** [comment]
I download this directory on Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-34-generic x86_64) 

excute 
```
git clone https://github.com/vimagick/dockerfiles.git
cd dockerfiles/pptpd/
modprobe nf_conntrack_pptp nf_nat_pptp
docker-compose up -d
```

config files and docker-compose.yml is default 
https://github.com/vimagick/dockerfiles/blob/master/pptpd/docker-compose.yml


there seems no debug message avaliable
```
~/pptpd# docker-compose run --rm pptpd sh
/ # pptpd --debug --fg
/ #
/ # exit
```

**Comment by vimagick** [comment]
I just tested on my VPS (Debian jessie):

```
$ cd ~/fig/pptpd/
$ tree
├── chap-secrets
├── docker-compose.yml
├── pptpd.conf
└── pptpd-options
$ docker-compose up -d
$ docker-compose logs -f
Attaching to pptpd_pptpd_1
pptpd_1  | + iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
pptpd_1  | + pptpd
pptpd_1  | + syslogd -n -O /dev/stdout
pptpd_1  | Aug 23 02:23:03 4f9a7d5d39f5 syslog.info syslogd started: BusyBox v1.24.2
pptpd_1  | Aug 23 02:23:03 4f9a7d5d39f5 daemon.info pptpd[9]: MGR: Manager process started
pptpd_1  | Aug 23 02:23:03 4f9a7d5d39f5 daemon.info pptpd[9]: MGR: Maximum of 100 connections available
```

The log is sent to `syslog`, so we cannot see it on screen.

**Comment by vimagick** [comment]
I just tested on my VPS (Debian jessie):

```
$ cd ~/fig/pptpd/
$ tree
├── chap-secrets
├── docker-compose.yml
├── pptpd.conf
└── pptpd-options
$ docker-compose up -d
$ docker-compose logs -f
Attaching to pptpd_pptpd_1
pptpd_1  | + iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
pptpd_1  | + pptpd
pptpd_1  | + syslogd -n -O /dev/stdout
pptpd_1  | Aug 23 02:23:03 4f9a7d5d39f5 syslog.info syslogd started: BusyBox v1.24.2
pptpd_1  | Aug 23 02:23:03 4f9a7d5d39f5 daemon.info pptpd[9]: MGR: Manager process started
pptpd_1  | Aug 23 02:23:03 4f9a7d5d39f5 daemon.info pptpd[9]: MGR: Maximum of 100 connections available
```

The log is sent to `syslog`, so we cannot see it on screen.

**Comment by vimagick** [comment]
I just tested on my VPS (Debian jessie):

```
$ cd ~/fig/pptpd/
$ tree
├── chap-secrets
├── docker-compose.yml
├── pptpd.conf
└── pptpd-options
$ docker-compose up -d
$ docker-compose logs -f
Attaching to pptpd_pptpd_1
pptpd_1  | + iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
pptpd_1  | + pptpd
pptpd_1  | + syslogd -n -O /dev/stdout
pptpd_1  | Aug 23 02:23:03 4f9a7d5d39f5 syslog.info syslogd started: BusyBox v1.24.2
pptpd_1  | Aug 23 02:23:03 4f9a7d5d39f5 daemon.info pptpd[9]: MGR: Manager process started
pptpd_1  | Aug 23 02:23:03 4f9a7d5d39f5 daemon.info pptpd[9]: MGR: Maximum of 100 connections available
```

The log is sent to `syslog`, so we cannot see it on screen.

**Comment by newrey** [comment]
maybe version effect?
My
Docker version 1.12.1, build 23cf638
docker-compose version 1.8.0, build f3628c7

**Comment by newrey** [comment]
docker-compose logs -f
Attaching to pptpd_pptpd_1
pptpd_1  | + iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
pptpd_1  | + pptpd
pptpd_1  | + iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
pptpd_1  | + pptpd
pptpd_1  | + iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
pptpd_1  | + pptpd
pptpd_1  | + iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
pptpd_1  | + pptpd
pptpd_1  | + iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
pptpd_1  | + pptpd
pptpd_1  | + iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
pptpd_1  | + pptpd
pptpd_1  | + iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
pptpd_1  | + pptpd
pptpd_1  | + iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
pptpd_1  | + pptpd
pptpd_1  | + iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
pptpd_1  | + pptpd
^CERROR: Aborting.

**Comment by vimagick** [comment]
It tested on other VPS (Ubuntu 14.04.1 + Docker 1.12.0).

```
$ docker-compose up -d
$ docker-compose logs -f
Attaching to pptpd_pptpd_1
pptpd_1  | + iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
pptpd_1  | + pptpd
pptpd_1  | + syslogd -n -O /dev/stdout
pptpd_1  | Aug 23 02:35:45 ae4bd7dfc289 syslog.info syslogd started: BusyBox v1.24.2
```

**Comment by newrey** [comment]
ok ,I will try 14.04

**Comment by newrey** [comment]
same issue.but i find another docker container works.

**Comment by vimagick** [comment]
Please reopen the issue if you have any question.
