### ISSUE TITLE
Unable to upload files larger than 1MB

### ISSUE THREAD

**Issue by Pacoboyd** [vimagick/dockerfiles#27]
Unable to upload files larger than 1MB in size.

I have made the changes noted here, including the nginx changes and cannot upload files larger that 1MB.

https://www.dokuwiki.org/faq:uploadsize

**Comment by Pacoboyd** [comment]
Found the issue, the problem was in my nginx reverse proxy.  I also had to add client_max_body_size 50M; into my reverse proxy conf file to fix the issue.

**Comment by vimagick** [comment]
The nginx config inside the image:

    client_max_body_size 4M;

You can mount your own `nginx.conf` via volume.

**Comment by vimagick** [comment]
Please reopen the issue if you have any question.
