### ISSUE TITLE
Is there a way to set VPN PSK value ?

### ISSUE THREAD

**Issue by Wyvern** [vimagick/dockerfiles#30]
Such as VPN_PSK environment variable support, please let me know. Thanks!

**Comment by vimagick** [comment]
There's no `VPN_PSK` inside `vimagick/strongswan`.
It only has `VPN_P12_PASSWORD` for private key protection.

Please take a look at [init.sh](https://github.com/vimagick/dockerfiles/blob/master/strongswan/init.sh).
