### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by ynvtlmr** [vimagick/dockerfiles#36]
Have you considered rebuilding this scrapyd image with Python3?

**Comment by vimagick** [comment]
Yes, I'll create a new tag for python3 in the future.
However, many scrapy projects are based on python2.

**Comment by gavinyipeiwang** [comment]
Missing bind_address = 0.0.0.0 in scrapyd.

**Comment by vimagick** [comment]
@gavinyipeiwang Thanks. Fixed.
