### ISSUE TITLE
share maintain experince

### ISSUE THREAD

**Issue by yangxuan8282** [vimagick/dockerfiles#37]
hi, your dockerfile is awesome, really long lists and still active updating
How did you maintain this ( especially for raspberry pi )? If you use CI like drone or travis-ci , but haven't found `yml` file?

**Comment by vimagick** [comment]
I maintain these dockerfiles by hand. I'll try CI in the future.

**Comment by yangxuan8282** [comment]
thanks for hard works
辛苦了

**Comment by yangxuan8282** [comment]
@vimagick 
which drone plugins do use on raspberry pi?
I use `armhfplugins/git` for git clone, but got issues:

```
standard_init_linux.go:178: exec user process caused "exec format error"
```

**Comment by vimagick** [comment]
I failed to run drone on pi.
See this issue: armswarm/drone#1

**Comment by yangxuan8282** [comment]
I guess that image failed to build sqlite3 dependency, maybe use mysql maybe work.

**Comment by vimagick** [comment]
Yes. I've built the docker myself. However one of essential plugins didn't work.

See this issue: armswarm/drone-docker#1

**Comment by yangxuan8282** [comment]
I used to compile it myself, not work either. and I also have try several other image, such as armdrone/drone, armhfbuild/drone, but all failed. I really wonder if somebody could run it on pi.
Currently I install drone on vultr, and after run:

```
docker run --rm --privileged multiarch/qemu-user-static:register
```

x64 vps capable building arm image, but seems after that `drone secret` can't store passwd correctly.

so I really want to setup drone server and client on raspberry pi itself.

**Comment by yangxuan8282** [comment]
@vimagick have you ever tried run gitlab runner on pi?

**Comment by vimagick** [comment]
Gitlab is very slow on pi.
