### ISSUE TITLE
why do you only expose the UDP port?How to set up shadowVPN relay?

### ISSUE THREAD

**Issue by digitaltwt** [vimagick/dockerfiles#43]
I see your dockerfile of ShadowVPN, you only expose the UDP port，why do you only expose the UDP port?
I want to set up ShadowVPN relay, but i don't have any solution,if i only use iptables to forward the TCP/UDP port,  i worry about bad performance .

**Comment by vimagick** [comment]
ShadowVPN only listens on port `1123/udp`.
I'm not quite sure, please check it out yourself.
