### ISSUE TITLE
cannot connect to a running vimagick/scrapyd container anymore

### ISSUE THREAD

**Issue by bartaelterman** [vimagick/dockerfiles#54]
Hi,

I built a scrapyd image based on yours a couple of months ago and it served me well. I now want to rebuild that image, but when I start a container as `docker run -p 6800:6800 vimagick/scrapyd` I don't get a response when I go to `localhost:6800`. Should I run the container differently? By the way, I am not running it with `docker-compose`, I'll run it on kubernetes.

Thanks a lot!

**Comment by vimagick** [comment]
Make sure you're using latest image.
Try to run container without kubernetes.

**Comment by bartaelterman** [comment]
Thanks for your response. I am currently running the latest image (as it is pulled by docker when I execute the `docker run` command shown above) without kubernetes. But in the end, I'll have to deploy it there. I am running with docker for mac.

**Comment by bartaelterman** [comment]
Sorry, I removed the image and ran the docker run command again. The image is pulled again and now I can connect to the running container.
