### ISSUE TITLE
django container: volume app/data is exposed but does nothing.

### ISSUE THREAD

**Issue by flq** [vimagick/dockerfiles#58]
Is there any way to persist data between container restarts ?

**Comment by vimagick** [comment]
[Dockerfile][1] for django-cms was created long time ago.
Latest program maybe store data at another location.
I'll take a look at it.
Thanks

[1]: https://github.com/vimagick/dockerfiles/blob/master/django-cms/Dockerfile

**Comment by flq** [comment]
Don't worry, at least for me
