### ISSUE TITLE
Questions about OpenRefine dockerfile

### ISSUE THREAD

**Issue by clombion** [vimagick/dockerfiles#74]
I'm trying to understand some details about the OpenRefine dockerfile:

     FROM java:8-jre-alpine   
     MAINTAINER kev <noreply@easypi.pro>
     ENV OR_VERSION 2.8
     ENV OR_FILE openrefine-linux-${OR_VERSION}.tar.gz
     ENV OR_URL https://github.com/OpenRefine/OpenRefine/releases/download/${OR_VERSION}/${OR_FILE}
     WORKDIR /app
     RUN set -xe \
         && apk add --no-cache bash curl jq tar \
         && curl -sSL ${OR_URL} | tar xz --strip 1
     VOLUME /data
     WORKDIR /data
     EXPOSE 3333 
     ENTRYPOINT ["/app/refine"]
     CMD ["-i", "0.0.0.0", "-d", "/data"]

* Is there a reason why you're using `java:8-jre-alpine` isntead of `openjdk:8-jre-alpine` ? the java docker hub page says 

> This image is officially deprecated in favor of the openjdk image, and will receive no further updates after 2016-12-31 (Dec 31, 2016). Please adjust your usage accordingly.

* why do you install `jq` with `apk add`? You don't seem to use it elsewhere.
* why do you create the `/data` folder with `VOLUME` instead of `RUN mkdir /data`? Docker's staff say [this](https://github.com/moby/moby/issues/30647#issuecomment-277048695):

> When not naming your volume you generally mean: I don't "care" about its data, it's ok to remove after the container is removed.
> 
> So; if you want to stick with the data; use --volume <volumename>:/path/in/container

Using `VOLUME` in a Dockerfile makes `Docker run` create an unnamed volume for each container created from the base image. My problem with this are that: 
* this unnamed volume is not easily reusable, because it's a random string instead of a clean name. 
* each unnamed volume created by each `Docker run` also stays permanently unless your remember that you should use the  `--rm` option. 
* reusing the data in another container (for exemple a container with a jupyter notebook), using `--volume-from` has been deprecated in Docker compose 3.0+ in favor of named volumes

I think a workflow where the Docker volume mapped to the `/data` folder within the container is defined at runtime by the user is better. If the user forgets to map an external volume to the container, it's ok because openrefine has access to the host's filesystem, which makes it easy to save the data outside of the container. 

Thanks!

**Comment by vimagick** [comment]
You're right. This dockerfile was created years ago. I need to improve it.
