### ISSUE TITLE
Mantis install error

### ISSUE THREAD

**Issue by webfrank** [vimagick/dockerfiles#75]
Hi, after docker-compose I cannot configure Mantis as I got this error:

BAD
Does administrative user have access to the database? ( Server sent charset unknown to the client. Please, report to the developers )

**Comment by alexeyOnGitHub** [comment]
+1. I have the same issue with the current module. tried various passwords.

**Comment by zxnhl702** [comment]
Hi there
I have the same issue too.
I tried mysql:5.7 instead of mysql:latest, and it just worked fine.No more errors.LOL

**Comment by Penchung** [comment]
Thanks to zxnhl702.
It works with me too.

**Comment by GhoctM** [comment]
use 2.16.1
I encountered the same error with this version

**Comment by tsikerdekis** [comment]
An updated version with some additions. The 2.18 version still requires 5.7 db for this docker to work.

```
version: '3'
services:
  mantisbt:
    image: vimagick/mantisbt:latest
    volumes:
        - ./config:/var/www/html/config
    ports:
      - "80:80"
    links:
      - mysql
    restart: always
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
        - ./mysql-data:/var/lib/mysql
        - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bugtracker
      - MYSQL_USER=mantisbt
      - MYSQL_PASSWORD=mantisbt
    restart: always
  backup_mysql:
    image: jtilander/backup-db:latest
    environment:
      - DBTYPE=mysql
      - CONTAINER=mysql
      - USERNAME=root
      - PASSWORD=root
      - "CRONSCHEDULE=0 0 * * *"
      - DBNAME=bugtracker
      - DEBUG=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tmp/backup:/data
    command: cron
```

**Comment by konylee** [comment]
出现can't connect to MySQL server using '' (13)的错误，结果是 SELinux 不让 httpd 访问外网，一开始还以为是iptables造成的，关闭之后发现还是不行。

原因：
#getsebool -a | grep httpd

[root@centos]#getsebool -a | grep httpd
allow_httpd_anon_write --> off
allow_httpd_mod_auth_ntlm_winbind --> off
allow_httpd_mod_auth_pam --> off
allow_httpd_sys_script_anon_write --> off
httpd_builtin_scripting --> on
httpd_can_check_spam --> off
httpd_can_network_connect --> off
httpd_can_network_connect_cobbler --> off
httpd_can_network_connect_db --> off
httpd_can_network_memcache --> off
httpd_can_network_relay --> off
httpd_can_sendmail --> off
httpd_dbus_avahi --> on
httpd_enable_cgi --> on
httpd_enable_ftp_server --> off
httpd_enable_homedirs --> off
httpd_execmem --> off
httpd_read_user_content --> off
httpd_setrlimit --> off
httpd_ssi_exec --> off
httpd_tmp_exec --> off
httpd_tty_comm --> on
httpd_unified --> off
httpd_use_cifs --> off
httpd_use_gpg --> off
httpd_use_nfs --> off
 
发现 httpd_can_network_connect_db --> off
 
解决方案：
#/usr/sbin/setsebool -P httpd_can_network_connect_db on
