### ISSUE TITLE
(vimagick/json-server) local host port binding

### ISSUE THREAD

**Issue by liquidcowgithub** [vimagick/dockerfiles#88]
Hi :)

The sample docker-compose.yml in the docs for vimagick/json-server did not work for me out the box. Was not able to hit http://localhost:3000 (the json-server home page)

Not sure if this is an issue directly related to the setup of this image, or the setup of docker environment running the vimagick/json-server container?

Modifying the docker-compose.yml to add the `--host 0.0.0.0` flag to json-server fixed this:

json-server:
  image: vimagick/json-server
  command: -w db.json --host 0.0.0.0
  ports:
    - "3000:3000"
  volumes:
    - ./db.json:/app/db.json
  restart: always

OS: OSX 10.13.6
Docker engine version: 18.06.0-ce
Compose version: 1.22.0

**Comment by tvld** [comment]
@liquidcowgithub Thanks; I needed that as well ...

**Comment by tulasirm** [comment]
Need it to me as well, that would be great help if you can guide me
