### ISSUE TITLE
Unable to run json-server properly 

### ISSUE THREAD

**Issue by abhi18av** [vimagick/dockerfiles#91]
Hi @vimagick 

I was trying to run `json-server` using the configs mentioned here https://hub.docker.com/r/vimagick/json-server/ but for some reason when I use the API client to test the generated API from `db.json` it's not working.

Here's the error message thrown by `httpie` 

```sh

Abhinavs-MacBook-Pro:code eklavya$ http GET :3000/posts

http: error: ConnectionError: ('Connection aborted.', BadStatusLine("''",)) while doing GET request to URL: http://localhost:3000/posts

```

**Comment by vimagick** [comment]
```
json-server [options] <source>

Options:
  --config, -c       Path to config file           [default: "json-server.json"]
  --port, -p         Set port                                    [default: 3000]
  --host, -H         Set host                             [default: "localhost"]
```

Latest version of json-server doesn't bind `0.0.0.0` (all interfaces).

I'll update the Dockerfile.

Thanks!
